apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: grype-vulnerability-scan

spec:
  description: >-
    Scan an SBOM or container image for known vulnerabilities
  params:
  - name: input
    description: The image reference or SBOM file to scan
  - name: grype-image
    description: The grype image to use to perform the vulnerability scan
    # default: 'docker.io/anchore/grype:v0.21'
    default: 'ghcr.io/wagoodman/grype:dev'
  - name: extra-args
    type: array
    default: []

  workspaces:
  - name: scan-target
    optional: true
  - name: output

  results:
    - name: report-filename
      description: The name of the vulnerability scan report file generated in the output workspace

  steps:
  - name: vulnerability-scan
    image: $(params.grype-image)
    command:
    - /grype
    - $(params.extra-args[*])
    - -vv
    - $(params.input)
    - -ojson
    - -f$(workspaces.output.path)/vulnerability-scan.json

  # TODO: make this filename configurable?
  - name: capture-output-report-filename
    image: bash:latest
    script: |
      #!/usr/bin/env bash
      echo vulnerability-scan.json | tee $(results.report-filename.path)