
[tool.poetry]
name = "whiteout-content"
version = "0.1.0"
description = ""
authors = ["Alex Goodman <alex.goodman@anchore.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
