apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: syft-generate-sbom

spec:
  description: >-
    Generate an SBOM from a container image
  params:
  - name: image
    description: Name (reference) of the container image
  - name: image-path
    description: path to the OCI image locally
  - name: output-format
    description: The SBOM format to use (json, spdx, spdx-json, cyclonedx)
    default: json
  - name: syft-image
    description: The syft image to use to generate the SBOM
    # default: 'docker.io/anchore/syft:v0.21'
    default: 'ghcr.io/wagoodman/syft:dev'
  - name: cosign-image
    description: The cosign image to use
    default: 'gcr.io/projectsigstore/cosign:v0.6.0@sha256:2303322158802ec0452758578ac80801a3754ee9cb19c128fc5d1b2ec32fa2d2'
  - name: extra-args
    type: array
    default: []

  workspaces:
  - name: image-content
    optional: true
  - name: output

  results:
    - name: sbom-filename
      description: The name of the SBOM file generated in the output workspace

  steps:
  - name: generate-sbom
    image: $(params.syft-image)
    command:
    - /syft
    - $(params.extra-args[*])
    - -vv
    - oci-dir:$(params.image-path)
    # - -o$(params.output-format)
    - -f$(workspaces.output.path)/sbom.$(params.output-format)

  - name: attach-sbom
    image: $(params.cosign-image)
    command:
    - /bin/cosign
    - attach
    - sbom
    - -sbom
    - $(workspaces.output.path)/sbom.$(params.output-format)
    - $(params.image)

  # TODO: make this filename configurable?
  - name: capture-sbom-filename
    image: bash:latest
    script: |
      #!/usr/bin/env bash
      echo -n sbom.$(params.output-format) | tee $(results.sbom-filename.path)

